Introduced a cuisine selection drop down
cgurtner/ZHAW-PM3 pull request #16
Opened 2023-11-04 16:40 UTC by seitzm97

Drop down has been integrated and filters the locations according to the selected cuisine type.

2023-11-05 09:59 UTC, cgurtner requested changes

2023-11-05 09:59 UTC, cgurtner commented on frontend/app/CuisineFilter.js
> +    const cuisines = ['all', 'regional', 'italian', 'kebab', 'asian', 'mexican', 'chinese'];
This is way to restrictive; I implemented in the route `http://localhost:3000/explore` to list all cuisines if you click on the amenities of type `['restaurant', 'cafe', 'fast_food', 'biergarten']`.

I would map all of those cuisines into about 10 cuisines to choose from into a new mongodb field:

1. To not always have to import the whole list of amenities, create a new python script besides `run.py`.
2. Go over all types of the above amenities and recode the field `cuisine`. Do this with a mapping dict of the form:

```
cuisine_mapping = [
"arab;kebab: arab;kebab": "kebab, pizza"
]
```
key: the value that is in the data
value: the recoded value to store in a new field `cuisine_coded` (do not overwrite `cuisine`)

Let the mapping dict GPT do, otherwise your going to get crazy. Maybe GPT can generate the most relevant cuisine combinations out of the whole list.

3. As soon as you show the amenity list nearby, build you drop-down based on the available cuisines -> only show filters that actually are applicable.

2023-11-05 09:59 UTC, cgurtner commented on frontend/app/CuisineFilter.js
> +        <select
Nicely done; But I would show the drop down after the list of amenities is shown. It's a filter and not part of the search.

2023-11-05 09:59 UTC, cgurtner commented on frontend/app/LocationFetch.js
> +import React, { useState, useEffect } from 'react';
`React` does not need to be imported. Most recent version of NextJS do this implicitly.

2023-11-05 09:59 UTC, cgurtner commented on frontend/app/page.js
> +            onCuisineChange={setSelectedCuisine}
Don't introduce new props names if not necessary. Change `onCuisineChange={setSelectedCuisine}` to `setSelectedCuisine={setSelectedCuisine}`. It serves no purpose to introduce the prop name `onCuisineChange` if `setSelectedCuisine` is already clear enough.

2023-11-23 14:29 UTC, seitzm97 commented on frontend/app/LocationFetch.js
> +import React, { useState, useEffect } from 'react';
Fixed

2023-11-23 14:40 UTC, seitzm97 commented on frontend/app/CuisineFilter.js
> +        <select
Adapted accordingly

2023-11-23 14:41 UTC, seitzm97 commented on frontend/app/CuisineFilter.js
> +    const cuisines = ['all', 'regional', 'italian', 'kebab', 'asian', 'mexican', 'chinese'];
Pushed solution. Please review my last commit

2023-11-27 20:48 UTC, merged